"""Deterministic, non-LLM remediation for Architecture validation failures.

Unlike build/test/lint failures, "no tests/ directory", "no requirements.txt",
and "no README" aren't things an LLM fix-the-failing-check loop is suited
for — there's no failing assertion to reason about, just missing standard
scaffolding. Generating that scaffolding is template work, not judgment work,
so it's handled directly here: purely additive (never touches an existing
file), so nothing needs the backup/rollback machinery Loop uses for
LLM-proposed edits — there's nothing to restore, only a new file to remove if
something goes wrong.
"""
from __future__ import annotations

from app.core.project_context import ProjectContext

_README_NAMES = ("README.md", "README.rst", "README.txt")


def missing_scaffolding(project: ProjectContext) -> dict[str, str]:
    """Returns {relative_path: content} for whatever standard scaffolding
    Architecture validation flags as missing — only entries that don't
    already exist on disk. `has_tests_dir` already means "has at least one
    real test file", not just "the folder exists" (see project_context.py),
    so an empty leftover tests/ folder is correctly treated as missing."""
    files: dict[str, str] = {}

    if not project.has_tests_dir:
        files["tests/__init__.py"] = ""
        files["tests/test_placeholder.py"] = (
            "# Auto-generated by Loop Engineering: replace with real tests for this project.\n"
            "\n\n"
            "def test_placeholder():\n"
            "    assert True\n"
        )

    if not project.build_files:
        files["requirements.txt"] = (
            "# Auto-generated by Loop Engineering — no declared dependencies were\n"
            "# detected. Add this project's actual runtime dependencies here.\n"
        )

    if not any((project.root / name).exists() for name in _README_NAMES):
        files["README.md"] = f"# {project.root.name}\n\n_README generated automatically by Loop Engineering._\n"

    return files


def write_missing_scaffolding(project: ProjectContext) -> list[str]:
    """Writes whatever's missing and returns the relative paths actually
    created (skips anything that already exists, even if missing_scaffolding
    was computed slightly stale)."""
    created: list[str] = []
    for rel_path, content in missing_scaffolding(project).items():
        target = project.root / rel_path
        if target.exists():
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        created.append(rel_path)
    return created
